version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=corona-scare"
      - "POSTGRES_DB=corona-scare-db"
    ports:
    - "5432:5432"
